"""
api/briefing.py — DEPRECATED
============================
The AI Brief is now 100% rule-based and generated by quotes_daily.py into
predictions.json under the `daily_brief` key. No LLM is called anywhere in
the pipeline.

This endpoint is retained only to return a clean, explicit error for any
stale frontend still pointing at it, so we avoid opaque 500s. It can be
safely deleted once all clients have refreshed their cached index.html.
"""
from http.server import BaseHTTPRequestHandler
import json


class handler(BaseHTTPRequestHandler):

    def do_POST(self):
        self._gone()

    def do_GET(self):
        self._gone()

    def do_OPTIONS(self):
        self.send_response(200)
        self._cors()
        self.end_headers()

    def _gone(self):
        body = json.dumps({
            "error": "deprecated",
            "message": (
                "AI Brief is now served from predictions.json.daily_brief "
                "(rule-based, no LLM). This endpoint no longer exists."
            ),
        }).encode("utf-8")
        self.send_response(410)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self._cors()
        self.end_headers()
        self.wfile.write(body)

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def log_message(self, *args):
        pass
